# Generated by Django 6.0.3 on 2026-03-19 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Local Transfer"),
                            ("INTERNATIONAL", "International Transfer"),
                            ("CRYPTO", "Crypto Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                ("account_number", models.CharField(blank=True, max_length=50)),
                (
                    "crypto_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BTC", "Bitcoin"),
                            ("USDT_ETH", "USDT (Ethereum)"),
                            ("USDT_TRON", "USDT (Tron)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("crypto_address", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
