# Generated by Django 6.0.3 on 2026-03-19 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_transfer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transfer",
        ),
    ]
